### PR TITLE
Exclude content if null

### PR DESCRIPTION
**Pull request by fabdsp**
Skip embedded content if null

### CODE REVIEW

**Comment by omansour** [comment]
:+1:  maybe you can give more explanations about the why ?

**Comment by fabdsp** [comment]
This change allows to have nullable embedded content.
if "content" is empty, the relation is ignored

**Comment by SylvG** [comment]
:+1: neeeed !

**Comment by UgoSansH** [comment]
:+1:

**Comment by mikaelrandy** [comment]
+:100:

**Comment by t-geindre** [comment]
:+1:

**Comment by adrienbrault** [comment]
If you want more advanced features, you could use the hateoas library https://github.com/willdurand/hateoas using the bundle https://github.com/willdurand/BazingaHateoasBundle .

This is basically a rewrite of the FSCHateoasBundle as a library, which fixes the biggest issues of the FSCHateoasBundle. It supports multiple way to exclude relations/links/embeds https://github.com/willdurand/hateoas#exclusion

**Comment by omansour** [comment]
txs @adrienbrault ! 

about this PR. Do you see anything against the merge ?

**Comment by adrienbrault** [comment]
Making https://github.com/TheFootballSocialClub/FSCHateoasBundle#conditionally-excluding-links work with embeds is probably better

**Pull request closed without merging**
