### PR TITLE
Update composer to use latests Symfony components

### PR DESCRIPTION
**Pull request by benja-M-1**
I don't how you want to manage versions of this bundle but I needed it in a Symfony project that follows the master branch.

### CODE REVIEW

**Comment by adrienbrault** [comment]
Maybe something like `>=2.0,<2.3-dev` or `>=2.1,<2.3-dev`. This constraint is used by FOSRestBundle https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/composer.json

**Comment by adrienbrault** [comment]
FYI, I lost write access to this repository because of issues in the company. In the meantine, composer is hooked to adrienbrault/FSCHateoasBundleFork, i'll merge your PRs there

EDIT: issue fixed :)

**Comment by baldurrensch** [comment]
@adrienbrault Can we talk on IRC when you have time?

**Comment by stof** [comment]
@benja-M-1 forcing 2.2 is a bad idea

**Comment by benja-M-1** [comment]
I agree but that was for my needs. I'll update this PR with what @adrienbrault suggested : `>=2.1,<2.3-dev`

**Comment by lsmith77** [comment]
+1 for `>=2.1,<2.3-dev`

**Pull request closed without merging**
