### PR TITLE
exclude form-serializer versions with symlink

### PR DESCRIPTION
**Pull request by JJK801**
Hi guys,

As form-serializer got some versions with a symlink which break our satis, this will ignore those useless versions.

Thanks,

Jérémy

### CODE REVIEW

**Comment by omansour** [comment]
related to https://github.com/adrienbrault/form-serializer/issues/5

**Comment by stof** [comment]
you should use `~0.1.2` which will match the same range

**Comment by JJK801** [comment]
@stof you're right, that's done

**Comment by adrienbrault** [comment]
thanks!

**Pull request merged**
